service: backend
org: ankan5415
app: spotlightme

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http: GET /
    environment:
      AIRTABLE_KEY: ${param:AIRTABLE_KEY}

resources:
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Comment: Backend cache
          DefaultCacheBehavior:
            TargetOriginId: AirtableProxy
            ViewerProtocolPolicy: "redirect-to-https"
            DefaultTTL: 30
            ForwardedValues:
              QueryString: false
          Enabled: true
          Origins:
            - Id: AirtableProxy
              DomainName:
                Fn::Join:
                  - "."
                  - - Ref: ApiGatewayRestApi
                    - execute-api.us-east-1.amazonaws.com
              OriginPath: /dev
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only
